version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: services/user_service/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:Minixs62795@@db:5432/hired_db
    restart: always

  frontend:
    build:
      context: ./hired_io_client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Minixs62795@@
      POSTGRES_DB: hired_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

volumes:
  postgres_data:
